name: ci

on:
  push:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to ghcr.io
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.REGISTER_USERNAME }}
          password: ${{ secrets.REGISTER_TOKEN }}
      - name: Create Credentials
        id: create_credentials
        run: |
          mkdir .docker
          echo ${{ secrets.PGPASSWORD }} > .docker/db-access.env
          echo ${{ secrets.POSTGRES_PASSWORD }} > .docker/db-creation.env
          echo ${{ secrets.ADMIN_PASSWORD }} > .docker/odoo.env
      - name: Build and push
        id: build_and_push
        run: |
          docker-compose --file prod.yaml --project-name odoo up -d --build --remove-orphans
          docker-compose --file prod.yaml --project-name odoo down
          docker image list
          docker tag odoo_odoo:latest ghcr.io/sergioshopifydev/doodba_odoo15:${{ github.ref_name }}-${{ github.sha }}
          docker tag odoo_odoo:latest ghcr.io/sergioshopifydev/doodba_odoo15:${{ github.ref_name }}-latest
          docker push ghcr.io/sergioshopifydev/doodba_odoo15:${{ github.ref_name }}-${{ github.sha }}
          docker push ghcr.io/sergioshopifydev/doodba_odoo15:${{ github.ref_name }}-latest
